// Generated by CoffeeScript 1.7.1
(function() {
  var env, express;

  express = require("express");

  env = {
    staticurl: "isnt.so",
    app: express(),
    plugins: ['auth'],
    dir: __dirname,
    emaildomain: 'darwin.email',
    DNSurl: "http://sandbox.rest.easydns.net/mail/maps/darwin.email",
    DNSuser: "OUR_API_TOKEN_HERE",
    DNSpass: "YOUR_API_KEY_HERE",
    basetemps: [
      {
        selector: "#boilerplate-container",
        filename: "dmail.jade"
      }
    ],
    s3: {
      key: 'AKIAICFLGBIGUIP4WEBA',
      secret: 'BJxqKfP5bkYDd8YDuYQwvV1Xqipw3hDXtaaNI9AY',
      bucket: 'isnt.so'
    }
  };

  exports.env = env;

  exports.setRoutes = function() {
    return require('./dmail_routes')(env);
  };

}).call(this);

//# sourceMappingURL=dmail_app.map
