// Generated by CoffeeScript 1.7.1
(function() {
  var addTag, callAfter, callFirst, editInPlace, looksLikeImage, runLoginAnim, tidyPix, which_route;

  callFirst = function() {
    return true;
  };

  tidyPix = function($context) {
    return $("div.story").not('.alreadytidied').each(function() {
      var $i, $t, s;
      $(this).addClass('alreadytidied');
      $t = $(this).find(".teaser");
      $i = $(this).find("img.image");
      s = $i != null ? $i.attr('src') : void 0;
      if ($t.text().length) {
        if (s != null ? s.length : void 0) {
          return $i.wrap("<div class='imgwrapper'>");
        } else {
          return $i.remove();
        }
      } else {
        if (s != null ? s.length : void 0) {
          return $i.wrap("<p align='center'>");
        }
      }
    });
  };

  callAfter = function(route) {
    tidyPix();
    $("span.tags").click(function() {
      return location.hash = "/tag/" + ($(this).text());
    });
    return setupComments(route);
  };

  runLoginAnim = function(o) {
    if (o) {
      $("i.maybe-login").removeClass('icon-signin').addClass('icon-signout');
      if ("admin" === o.handle) {
        return $("i.maybe-edit").addClass('icon-edit');
      }
    } else {
      $("i.maybe-edit").removeClass('icon-edit');
      return $("i.maybe-login").addClass('icon-signin').removeClass('icon-signout');
    }
  };

  editInPlace = function($d, tag, id) {
    return $d.find(tag + "#" + id).click(function() {
      var r, v;
      r = "input";
      v = $(this).text();
      if (tag === "p") {
        r = "textarea";
        $(this).replaceWith("<" + r + " id='" + id + "' class='canhide'>" + v + "</" + r + ">");
      } else {
        $(this).replaceWith("<" + r + " id='" + id + "' class='canhide' value='" + v + "'/>");
      }
      return $d.find(r + "#" + id).focus().blur(function() {
        v = $(this).val();
        if (v.length) {
          $(this).replaceWith("<" + tag + "	id='" + id + "' class='canhide'>" + v + "</" + tag + ">");
          if (id === "image") {
            $d.find("img#postimg").attr("src", v).removeClass("hide4now");
          }
        } else {
          if (id === "image") {
            $d.find("img#postimg").addClass("hide4now");
          }
        }
        return editInPlace($d, tag, id);
      });
    });
  };

  looksLikeImage = function(u) {
    var lastfive, lastfour;
    lastfour = u.substr(u.length - 4).toLowerCase();
    lastfive = u.substr(u.length - 5).toLowerCase();
    return lastfour === ".jpg" || lastfour === ".gif" || lastfour === ".png" || lastfive === "jpeg";
  };

  addTag = function(t) {
    var $t;
    if (!t || !t.length) {
      return;
    }
    $t = $("<span class='tags'>" + t + "<i class='icon-remove-sign'></i></span>");
    $('.intaglist .taglist').append($t);
    return $t.find('i').click(function() {
      return $(this).parent().remove();
    });
  };

  which_route = "";

  $(function() {
    runWithAuth(runLoginAnim, true);
    justsayUpdate(callAfter);
    callAfter();
    $("i.maybe-edit").hover((function() {
      return $(this).addClass("hoverbutt");
    }), (function() {
      return $(this).removeClass("hoverbutt");
    })).click(function() {
      var $d, user;
      user = runWithAuth();
      if (!user || "admin" !== user.handle) {
        return false;
      }
      $("body").prepend(justGetFrag("inform.jade"));
      $d = $("div#modal");
      $("i.icon-remove-sign").hover((function() {
        return $(this).addClass("hoverbutt");
      }), (function() {
        return $(this).removeClass("hoverbutt");
      })).click(function() {
        $d.remove();
        return $("div#modalbg").remove();
      });
      editInPlace($d, "h1", "title");
      editInPlace($d, "p", "description");
      editInPlace($d, "span", "image");
      $d.find("input#url").change(function() {
        var u;
        u = $(this).val();
        if (u.substr(0, 7) !== "http://") {
          u = "http://" + u;
        }
        $(this).parent().find(".canhide").addClass("hide4now");
        if (looksLikeImage(u)) {
          $d.find("span#image").text(u);
          $d.find("img#postimg").attr("src", u).removeClass("hide4now").parent().removeClass("hide4now");
          return $d.find("button").removeClass("hide4now");
        } else if ($(this).val().length) {
          return justsayMakeTheCall("/consider/" + encodeURIComponent(u), function(call, ansarr) {
            $d.find("span#image").text(ansarr[0].image);
            $d.find("img#postimg").attr("src", ansarr[0].image);
            $d.find("p#description").text(ansarr[0].description);
            $d.find("h1#title").text(ansarr[0].title);
            $d.find(".hide4now").removeClass("hide4now");
            return true;
          });
        }
      });
      $d.find("button").click(function() {
        var $tags, payload, u;
        u = $d.find("input#url").val();
        if (u.substr(0, 7) !== "http://") {
          u = "http://" + u;
        }
        payload = {
          url: u,
          comment: $d.find("textarea#comment").val()
        };
        if (!looksLikeImage(u)) {
          payload.image = $d.find("span#image").text();
          payload.description = $d.find("p#description").text();
          payload.title = $d.find("h1#title").text();
          $tags = $('.intaglist .taglist').find('.tags');
          if ($tags.length) {
            payload.tags = [];
            $tags.each(function() {
              return payload.tags.push($(this).text());
            });
          }
        }
        return justsayAJAJ("/blog/", (function() {
          $d.remove();
          return $("div#modalbg").remove();
        }), (function(err) {
          return $d.find("input#url").addClass("error");
        }), payload);
      });
      $d.find('input.intag, select.intag').change(function() {
        addTag($(this).val());
        return $(this).val('');
      });
      return justsayAJAJ("/tags", function(tags) {
        var tag, _i, _len, _results;
        _results = [];
        for (_i = 0, _len = tags.length; _i < _len; _i++) {
          tag = tags[_i];
          _results.push($d.find('select.intag').append("<option value='" + tag + "'>" + tag + "</option>"));
        }
        return _results;
      });
    });
    $("i.maybe-login").hover((function() {
      return $(this).addClass("hoverbutt");
    }), (function() {
      return $(this).removeClass("hoverbutt");
    })).click(function() {
      if (runWithAuth()) {
        runWithAuth(null);
        return runLoginAnim();
      } else {
        return runWithAuth(runLoginAnim);
      }
    });
    return $(window).scroll(function() {
      return $("div.paginationlink").find("a.nextlink").each(function() {
        var $a, h;
        $a = $(this);
        h = $a.attr("href");
        if (h && h.length) {
          if ($(window).scrollTop() + $(window).height() > $a.offset().top + 53) {
            return justsayMakeTheCall(h, (function(call, $temp, $dest) {
              $a.parent().replaceWith($temp.html());
              tidyPix();
              return true;
            }), callFirst);
          }
        }
      });
    });
  });

}).call(this);
