// Generated by CoffeeScript 1.6.2
(function() {
  var i, sharedConfig, wscfg, wserver, _i, _len, _ref;

  require('longjohn');

  wserver = require('./justsayno.de/wserver');

  wscfg = require('./wscfg').options;

  if (wscfg.proxy_name) {
    wserver.getProxy(wscfg.proxy_name, wscfg.proxy_port, wscfg.clandestine, wscfg.proxies);
  } else {
    wserver.setProxy(wscfg.proxy_port, wscfg.ip, wscfg.clandestine);
  }

  sharedConfig = {
    mailopts: wscfg.mailopts,
    adminemail: wscfg.adminemail
  };

  _ref = wscfg.apps;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    i = _ref[_i];
    if (i.appname === 'static') {
      sharedConfig.localurl = i.dname;
    }
  }

  wserver.setupServer(wscfg.server_port, wscfg.apps, wscfg.ip, wscfg.setuid, sharedConfig);

}).call(this);

/*
//@ sourceMappingURL=webserver.map
*/
