// Generated by CoffeeScript 1.6.2
(function() {
  var options;

  options = {
    clandestine: "You'll>never<guess,",
    apps: [
      {
        dname: 'static.loc',
        appname: 'static'
      }, {
        dname: 'nonukes.loc',
        appname: 'nonukes'
      }
    ],
    server_port: 80,
    proxy_port: 8780,
    proxy_name: '',
    proxies: [],
    adminemail: 'justin@justat.in',
    mailopts: {
      host: 'mail.justat.at',
      port: 587,
      auth: {
        user: 'just@justat.at',
        pass: 'thisisnotmyrealpassword'
      }
    },
    setuid: 'jtnt'
  };

  exports.options = options;

}).call(this);

/*
//@ sourceMappingURL=wscfg.map
*/
