// Generated by CoffeeScript 1.9.3
(function() {
  var callAfter, callFirst, runLoginAnim, setupRegoForm, validateRegoForm, which_route;

  callFirst = function() {
    return true;
  };

  validateRegoForm = function($f) {
    var $field, mail, pass;
    $field = $f.find("input[type='password']");
    pass = $field.val();
    if (!$f.hasClass('edit')) {
      if ((pass != null ? pass.length : void 0) < 8) {
        return $field;
      }
    }
    $field = $f.find("input.email");
    mail = $field.val();
    if ((mail != null ? mail.length : void 0) === 0) {
      if ($f.hasClass('edit')) {
        return null;
      } else {
        return $field;
      }
    }
    if (!mail.match(/^[a-zA-Z0-9_\-\.]+@([a-zA-Z0-9-]+\.)+[a-zA-Z0-9-]+$/)) {
      return $field;
    }
    return null;
  };

  setupRegoForm = function($f) {
    if (!($f != null ? $f.length : void 0)) {
      return;
    }
    $f.find('.regoitem input').focus(function() {
      $(this).removeClass('error');
      $(this).parent().find('i.icon-info-sign').fadeIn('slow');
      $(this).parent().find('p.desc').hide();
      return $(this).parent().find('div.desc').fadeIn();
    }).blur(function() {
      $(this).parent().find('i.icon-info-sign').hide();
      return $(this).parent().find('.desc').fadeOut();
    }).change(function() {
      var disflag;
      $f.find('div.errmsg').text('');
      disflag = true;
      $f.find('input').each(function() {
        if (this.type === 'text' || this.type === 'password') {
          if ($(this).val().length) {
            return disflag = false;
          }
        }
      });
      return $f.find("[type='submit']").prop('disabled', disflag);
    });
    $f.find('i.icon-info-sign').hover(function() {
      $(this).parent().find('div.desc').hide();
      return $(this).parent().find('p.desc').fadeIn();
    }, function() {
      $(this).parent().find('p.desc').hide();
      if ($(this).css('display') !== 'none') {
        return $(this).parent().find('div.desc').fadeIn();
      }
    });
    $f.find('input.cancel').click(function() {
      if ($f.hasClass('edit')) {
        return location.hash = "/";
      } else {
        return location.hash = '/deregister';
      }
    });
    return $f.find("[type='submit']").click(function() {
      var $error;
      if ($error = validateRegoForm($f)) {
        $f.find('div.errmsg').text("Invalid " + ($error.attr('name')));
        $error.addClass('error');
      } else {
        justsayAJAJ($f.attr("action"), function() {
          if ($f.hasClass('edit')) {
            if (!$f.find("input[type='text']").val().length) {
              return location.hash = "/";
            }
          }
          return location.hash = "/confirm";
        }, function(errstr, code) {
          var type;
          if (code === 409) {
            type = 'text';
          } else {
            type = 'password';
          }
          $f.find("input[type='" + type + "']").addClass('error');
          return $f.find('div.errmsg').text(errstr);
        }, $f.serialize());
      }
      return false;
    });
  };

  which_route = '';

  callAfter = function(route) {
    var user;
    which_route = route;
    if (!(route != null ? route.length : void 0)) {
      return location.hash = "/register";
    }
    $("a.logout").click(function() {
      return runWithAuth(null);
    });
    $("a.login").click(function() {
      if (runWithAuth()) {
        return runWithAuth(null);
      } else {
        return runWithAuth(runLoginAnim);
      }
    });
    user = runWithAuth();
    if (user) {
      if (which_route === ("user/" + user.handle)) {
        $('div#edithomebutt').text('\uf044');
      } else {
        $('div#edithomebutt').text('\uf015');
      }
    }
    $('div.rego input.handle').focus(function() {
      return $(this).removeClass('error');
    }).change(function() {
      $('div.rego div.errmsg').text('');
      return justsayAJAJ('/preregister', function(s) {
        return location.hash = '/registration';
      }, (function(_this) {
        return function(e) {
          $(_this).blur().addClass('error');
          return $('div.rego div.errmsg').text(e);
        };
      })(this), {
        handle: $(this).val()
      });
    });
    return setupRegoForm($('.registration form'));
  };

  runLoginAnim = function(o) {
    var ref;
    if (o) {
      if (which_route === o.handle) {
        $('div#edithomebutt').text('\uf044');
      } else {
        $('div#edithomebutt').text('\uf015');
      }
      $('div#edithomebutt').animate({
        marginLeft: '-3em'
      }, function() {
        return $('div#edithomebutt').animate({
          marginLeft: '0em'
        });
      });
    }
    if (o != null ? (ref = o.handle) != null ? ref.length : void 0 : void 0) {
      return location.hash = "/user/" + o.handle;
    }
    if (o != null ? o.handle : void 0) {
      return location.hash = "/registration";
    }
    return location.hash = "/register";
  };

  $(function() {
    $('div#edithomebutt').hover(function() {
      return $(this).addClass('hoverbutt');
    }, function() {
      return $(this).removeClass('hoverbutt');
    }).click(function() {
      var user;
      user = runWithAuth();
      if (user && which_route === ("user/" + user.handle)) {
        return location.hash = "/edit/" + user.handle;
      } else {
        return location.hash = "/user/" + user.handle;
      }
    });
    $('div#onoffbutt').hover(function() {
      if (runWithAuth()) {
        return $(this).addClass('offbutt');
      } else {
        return $(this).addClass('onbutt');
      }
    }, function() {
      return $(this).removeClass('onbutt').removeClass('offbutt');
    }).click(function() {
      if (runWithAuth()) {
        runWithAuth(null);
        return $('div#edithomebutt').animate({
          marginLeft: '-3em'
        });
      } else {
        return runWithAuth(runLoginAnim);
      }
    });
    runWithAuth(runLoginAnim, true);
    justsayUpdate(callAfter);
    return callAfter(location.hash);
  });

}).call(this);
