// Generated by CoffeeScript 1.7.1
(function() {
  var Schema, TagSchema, mongoose;

  mongoose = require("mongoose");

  Schema = mongoose.Schema;

  TagSchema = new Schema({
    name: String
  });

  mongoose.model("Tag", TagSchema);

  module.exports.name = "Tag";

  module.exports.schema = TagSchema;

}).call(this);

//# sourceMappingURL=tag.map
