// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(e, admdb) {
    var env;

    env = {
      app: require("express")(),
      dir: __dirname,
      appname: "admin",
      targetapp: e.appname,
      targetenv: e,
      staticurl: e.staticurl,
      localurl: e.localurl,
      basetemps: [
        {
          selector: "#boilerplate-container",
          filename: "admin.jade"
        }
      ]
    };
    return {
      env: env,
      setRoutes: function() {
        return require("./admin_routes")(env, e, admdb);
      }
    };
  };

}).call(this);

/*
//@ sourceMappingURL=admin.map
*/
