// Generated by CoffeeScript 1.7.1
(function() {
  window.runWithAuth = (function() {
    var doRunWithAuth, drawLogin, loudLogin, removeLogin, session_user, validateLogin;
    session_user = '';
    validateLogin = function($l) {
      var $c, $e, $h, $p;
      if (!($h = $l.find("[name='login']")).val().length) {
        return $h;
      }
      if (!($p = $l.find("[name='password']")).val().length) {
        return $p;
      }
      if (($c = $l.find("[name='confirm']")).length) {
        if ($c.val() !== $p.val()) {
          return $c;
        }
        if (!($e = $l.find("[name='email']")).val().length) {
          return $e;
        }
      }
      return null;
    };
    drawLogin = function() {
      var $l;
      $l = $(justGetFrag("auth.jade") || justGetFrag("auth.htm"));
      $("body").prepend($l);
      $l.find("input[type='text'],input[type='password']").focus(function() {
        return $(this).css("backgroundColor", "#fff");
      });
      if (_.isString(session_user)) {
        $l.find("input[name='login']").val(session_user);
      }
      return $l.find("form");
    };
    removeLogin = function() {
      $("div#loginpage").remove();
      return $("div#loginbackdrop").remove();
    };
    loudLogin = function(succ, fail) {
      var $login;
      $login = drawLogin();
      $login.find("[type='submit']").click(function(e) {
        var $error, newstuff;
        if ($(this).val() === "Register" && !$login.find("[name='confirm']").length) {
          newstuff = "<div class='expendable'>" + "<span>Confirm:</span> <input type='password' name='confirm' /><br>" + "<span>Email:</span> <input type='text' name='email' />" + "<div><i>we'll send you an activation email</i></div> </div>";
          $login.animate({
            height: "380px"
          });
          $login.find("input[name='password']").after($(newstuff));
          $login.find("input[name='register']").val("Submit");
          $login.attr("action", "/register");
        } else if ($(this).val() === "Login" && $login.find("[name='confirm']").length) {
          $login.animate({
            height: "240px"
          }).find("div.expendable").remove();
          $login.find("input[name='register']").val("Register");
          $login.attr("action", "/login");
        } else {
          if ($error = validateLogin($login)) {
            $error.css("backgroundColor", "#fcc");
          } else {
            justsayAJAJ($login.attr("action"), (function(o) {
              session_user = o;
              removeLogin();
              return succ();
            }), (function(s) {
              if (s != null ? s.length : void 0) {
                return $login.find("input[name='email'], input[name='login']").each(function() {
                  if ($(this).val() === s) {
                    $(this).css("backgroundColor", "#fcc");
                    return s = "";
                  }
                });
              } else {
                return $login.find("input[type='password']").css("backgroundColor", "#fcc");
              }
            }), $login.serialize());
          }
        }
        return false;
      });
      return $login.find("[name=cancel]").click(function() {
        removeLogin();
        return fail();
      });
    };
    doRunWithAuth = function(succ, fail, silent) {
      if (session_user.handle) {
        return succ();
      }
      return justsayAJAJ("/silent_login", (function(o) {
        session_user = o;
        return succ();
      }), function(o) {
        session_user = o;
        if (silent) {
          return fail();
        } else {
          return loudLogin(succ, fail);
        }
      });
    };
    if (!justGetFrag("auth.jade")) {
      justsayno.de.skeleta["auth.htm"] = "<div id='loginbackdrop'></div>\n<div id='loginpage'><div id='loginbox'>\n<form action='/login'>\n	Name: <input type='text' name='login' /><br>\n	Password: <input type='password' name='password' />\n		<div style='clear:both'>\n			<input type='submit' value='Login'/>\n			<input type='button' name='cancel' value='Cancel'/>\n			<input class='registerbutton' type='submit' name='register' value='Register'/></div>\n		<div class='reminder'>\n			<input type='checkbox' name='remember' />remember me on this computer</div>\n</form></div></div>\"";
    }
    return function(cb, silent) {
      if (_.isUndefined(cb)) {
        return (session_user.handle ? session_user : null);
      }
      if (!cb) {
        session_user = {};
        return justsayAJAJ("/logout");
      } else {
        return doRunWithAuth((function() {
          return cb(session_user);
        }), cb, silent);
      }
    };
  })();

}).call(this);
